apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zomato
  name: zomato-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
      containers:
      - name: cont1
        image: umredkarrohit09/mydockerproject:myzomatoimage
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: abc
spec:
  type: LoadBalancer
  selector:
    app: zomato
  ports:
    - port: 3000
